language: ruby

rvm:
 - 2.5
 - 2.6

gemfile:
 - gemfiles/rails-5.0.gemfile
 - gemfiles/rails-5.1.gemfile
 - gemfiles/rails-5.2.gemfile
 - gemfiles/rails-6.0.gemfile
 - gemfiles/rails-6.1.gemfile

before_install: "gem update bundler"

script: "bin/test"

notifications:
  email: false
