name: CI tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
#         disabled most of the very old tests, focussing on newer versions
#          # Ruby 2.5 supports up to Rails 6.1
#          - ruby: 2.5
#            gemfile: gemfiles/rails-5.0.gemfile
#          - ruby: 2.5
#            gemfile: gemfiles/rails-5.1.gemfile
#          - ruby: 2.5
#            gemfile: gemfiles/rails-5.2.gemfile
#          - ruby: 2.5
#            gemfile: gemfiles/rails-6.0.gemfile
#          - ruby: 2.5
#            gemfile: gemfiles/rails-6.1.gemfile
#
#          # Ruby 2.6 supports up to Rails 6.1
#          - ruby: 2.6
#            gemfile: gemfiles/rails-5.0.gemfile
#          - ruby: 2.6
#            gemfile: gemfiles/rails-5.1.gemfile
#          - ruby: 2.6
#            gemfile: gemfiles/rails-5.2.gemfile
#          - ruby: 2.6
#            gemfile: gemfiles/rails-6.0.gemfile
#          - ruby: 2.6
#            gemfile: gemfiles/rails-6.1.gemfile
#
#          # Ruby 3.3 supports Rails 7.0 and later
#          - ruby: 3.3
#            gemfile: gemfiles/rails-7.0.gemfile
          - ruby: 3.3
            gemfile: gemfiles/rails-7.1.gemfile
          - ruby: 3.3
            gemfile: gemfiles/rails-7.2.gemfile
          - ruby: 3.3
            gemfile: gemfiles/rails-8.0.gemfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install System Libraries
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle install --gemfile=${{ matrix.gemfile }} --retry=3

      - name: Run tests
        run: |
          mkdir -p test-reports
          CI=true BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle exec bin/test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: 'test-reports/**/*.xml'
          check_name: Rails tests report
          test_files_prefix: ${{ matrix.gemfile }}
          include_passed: true
